### ISSUE TITLE
Few remaining issues at v1.0.0

### ISSUE THREAD

**Issue by Cervator** [Terasology/Books#1]
Did some testing! Still a few issues to look for
- [x] The page indexing is off. I can click through a book to the right three times, then back only two times to get the front cover (page 1 is missing?)
- [x] Outright crashed once attempting to open a book, error below. Pretty sure it is from leaving one book on the last page then opening another.
- [x] Is the active page "sticky" and somehow leaking between entities? I think I could leave a book open on a specific page and a different book would then open to that page? Or maybe that's a red herring. Or the cause for the crash above
- [x] There is still some UI element that is eating `e` clicks. Try placing a chest when you spawn, without even having requested any book-related stuff via console. First `e` click does nothing (almost like it is being caught by something else / consumed early) then the second click opens the chest
- [x] Bookcase blocks still do not open, but still make the click noise. ~~~I wonder if that's related to the `e` click issue?~~~

Quite possibly some of these predate the recent overhaul by @Waterpicker. I just fixed a JSON formatting issue and put `-SNAPSHOT` back on the version number in module.txt (source should always be SNAPSHOT and Jenkins / release management handles the non-snaphots, lest things go boom). Also fixed some tabs -> spaces and a waaay outdated "craftPlace" thing

Actually, that appears to have fixed the `e` eating. Yay! I fixed something :-)

Crash log:

```
14:28:44.714 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] You received an item of Books:bluebook
14:29:23.882 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.terasology.books.rendering.nui.layers.BookScreen$3.get(BookScreen.java:145)
    at org.terasology.books.rendering.nui.layers.BookScreen$3.get(BookScreen.java:136)
    at org.terasology.rendering.nui.widgets.UILabel.getText(UILabel.java:65)
    at org.terasology.rendering.nui.widgets.UILabel.onDraw(UILabel.java:89)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:78)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:104)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:468)
    at org.terasology.engine.modes.StateIngame.renderUserInterface(StateIngame.java:234)
    at org.terasology.engine.modes.StateIngame.render(StateIngame.java:218)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:189)
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
    at org.terasology.engine.Terasology.main(Terasology.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
14:29:23.883 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
14:29:23.966 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
14:29:23.969 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
14:29:23.972 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
14:29:23.976 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
14:29:23.976 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
14:29:25.282 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
14:29:28.202 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"healthBar"},"position-bottom":{"target":"TOP","widget":"healthBar","offset":1}}}
14:29:28.203 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
14:29:28.226 [main] WARN  o.t.rendering.nui.skin.UISkinFormat - Failed to resolve UIWidget class UIInputBindButton, skipping style information
java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.terasology.books.rendering.nui.layers.BookScreen$3.get(BookScreen.java:145)
    at org.terasology.books.rendering.nui.layers.BookScreen$3.get(BookScreen.java:136)
    at org.terasology.rendering.nui.widgets.UILabel.getText(UILabel.java:65)
    at org.terasology.rendering.nui.widgets.UILabel.onDraw(UILabel.java:89)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:78)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:104)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:468)
    at org.terasology.engine.modes.StateIngame.renderUserInterface(StateIngame.java:234)
    at org.terasology.engine.modes.StateIngame.render(StateIngame.java:218)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:189)
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
    at org.terasology.engine.Terasology.main(Terasology.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
For more details, see the log files in J:\Dev\Terasology\Git\integrate\Terasology\logs\2016-06-18_14-21-06
```
##

**Comment by iojw** [comment]
@Cervator: I can't seem to able to replicate any of the issues you mentioned. I've looked at the code and tested it out and the page turning appears to work as expected. The current page resets on close and there's no crash of any sort when leaving one book on the last page and opening another.

I also didn't face the issue where the click sound was played, but the bookcase didn't open. Instead, I'm actually facing the issue where `e` clicks are getting eaten up. I suspect this is related to Terasology/JoshariasSurvival#15 as well... 

As with chests, a reliable way of replicating this issue is opening the bookcase and then closing it using `Esc`. First click does nothing, then the second click opens it. 

How strange... I'm very curious as to what changes were made that caused this issue to resurface since you mentioned that you managed to fix this issue before. I'll try to look into this.

**Comment by Cervator** [comment]
Oh I just noticed @Waterpicker submitted another commit 3 days after I entered that issue. So if it is fixed then cool! That's one item out of the way :-)

I think the click eating issue has two sides to it

* The actual issue around screens not closing correctly so the next `e` click is consumed. That's a bug we need to fix
* You can configure UIs to where they aggravate/minimize the issue. That could be as simple as opening it a different way, like right click or `i` click instead of `e` clicking a block, leaving the player more likely to close the UI "correctly" in some way that avoids the issue

**Comment by iojw** [comment]
@Cervator Just saw your comment right after I submitted a PR for it in the main repo 🙂. This should mean that all the issues here are fixed.

**Comment by Cervator** [comment]
Awesome, thanks! Checking back in later, leaving the house for a while now

**Comment by Cervator** [comment]
Closing as complete :-)
